# Generated by Django 2.1.1 on 2018-09-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=30, null=True, unique=True)),
                ('dept_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DutyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('birthday', models.DateField(null=True)),
                ('gender', models.CharField(max_length=30, null=True)),
                ('dept', models.CharField(max_length=30)),
                ('mphone', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
